#!/bin/bash

# make sure we are in a git repository
if [ "$(git rev-parse --is-inside-work-tree)" != "true" ]; then
	exit 1
fi

# validate arguments
if [ -z "${1}" -o -n "${2}" ]; then
	echo "Usage: git whose-branch branch_name"
	exit 0
fi

# find out whose branch ${1} is
branches="$(git for-each-ref --format='%(authorname)%09%(refname)' | tr ' ' '\001' | tr '\t' '\002')"
for i in ${branches[@]}; do
	author_ref_pair=( $(echo $i | tr '\002' ' ') )
	if [ "${author_ref_pair[1]}" == "refs/remotes/origin/${1}" ]; then
		echo "$(echo ${author_ref_pair[0]} | tr '\001' ' ')"
		exit 0
	fi
done

exit 1
