#!/bin/bash

# make sure we are in a git repository
if [ "$(git rev-parse --is-inside-work-tree)" != "true" ]; then
	exit 1
fi

# ignore multiple git commands and pass through actual command
# i.e. git git branch -> git branch
while [ "$1" == "git" ]; do
	shift
done
git $@
