#!/bin/bash

# make sure we are in a git repository
if [ "$(git rev-parse --is-inside-work-tree)" != "true" ]; then
	exit 1
fi

# validate arguments
if [ -z "${1}" -o -z "${2}" -o -n "${3}" ]; then
	echo "Usage: git branch-diff branch_name merge_base"
	exit 0
fi

# figure out what kind of ref branch_name is
ref_path_branch="refs/heads/"
if [[ "${1}" == *"/"* ]]; then
	ref_path_branch="refs/remotes/"
fi

# figure out what kind of ref merge_base is
ref_path_base="refs/heads/"
if [[ "${2}" == *"/"* ]]; then
	ref_path_base="refs/remotes/"
fi

# make sure branch to compare exists
if ! $(git show-ref --verify --quiet ${ref_path_branch}${1}); then
	echo "Error: Branch ${ref_path_branch}${1} does not exist! Please select an existing branch."
	exit 1
fi

# make sure merge_base branch exists
if ! $(git show-ref --verify --quiet ${ref_path_base}${2}); then
	echo "Error: Merge base ${2} does not exist. Nothing to compare to."
	exit 1
fi

git difftool -d $(git merge-base ${2} ${1}) ${1}

