#!/bin/bash

# make sure we are in a git repository
if [ "`git rev-parse --is-inside-work-tree`" != "true" ]; then
	exit 1
fi

git fetch || exit 1
git merge origin/develop || exit 1
git remote prune origin || exit 1
git push || exit 1
